=== RoseVar/InmobiliariaSAXJavaXML/Vargas_DAM2_M03_pt513_ los_XML-DTD-XSD/realestate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="realestate">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="estate" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
     <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="estate">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="type">
            <xs:simpleType>
            <xs:restriction base='xs:string'>
                <xs:enumeration value="House"/>
                <xs:enumeration value="Premise"/>
            </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element name="surface">
            <xs:simpleType>
                <xs:restriction base="xs:double">
                    <xs:minInclusive value="0"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element ref="address"/>
        <xs:element name="price">
            <xs:simpleType>
                <xs:restriction base="xs:double">
                    <xs:minInclusive value="0"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="address">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="street" type="xs:string"/>
        <xs:element name="number">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="0"/>
                    <xs:maxInclusive value="5000"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element name="floor">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="0"/>
                    <xs:maxInclusive value="50"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
        <xs:element name="door">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="0"/>
                    <xs:maxInclusive value="10"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== RoseVar/InmobiliariaSAXJavaXML/Vargas_DAM2_M03_pt513_SAX-XML/Resources/realstate.xml
<?xml version="1.0" encoding="UTF-8"?>
<realestate name="Inmobiliaria Roser" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="realestate.xsd">
    <estate id="45123">
        <type>Premise</type>
        <surface>215.15</surface>
        <address>
            <street>C/Roma</street>
            <number>38</number>
            <floor>5</floor>
            <door>2</door>
        </address>
        <price>205300.50</price>
    </estate>

    <estate id="23041">
        <type>House</type>
        <surface>80</surface>
        <address>
            <street>C/Venecia</street>
            <number>520</number>
            <floor>2</floor>
            <door>1</door>
        </address>
        <price>155300.50</price>
    </estate>

    <estate id="152863">
        <type>Premise</type>
        <surface>4512.12</surface>
        <address>
            <street>C/Florencia</street>
            <number>3</number>
            <floor>10</floor>
            <door>8</door>
        </address>
        <price>1500300.50</price>
    </estate>

    <estate id="35980">
        <type>House</type>
        <surface>80.50</surface>
        <address>
            <street>C/Verona</street>
            <number>125</number>
            <floor>4</floor>
            <door>4</door>
        </address>
        <price>175100.00</price>
    </estate>
</realestate>
